// File generated by flutterfire_cli.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        // Windows is not supported by Firebase
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCazebd3sohRpUUFvEgJOSmDQlLuYw61WM',
    appId: '1:158448736984:web:0aa13c812fbbf2419a55ad',
    messagingSenderId: '158448736984',
    projectId: 'nextstep-d7965',
    authDomain: 'nextstep-d7965.firebaseapp.com',
    storageBucket: 'nextstep-d7965.firebasestorage.app',
    measurementId: 'G-85L5528R2F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBMknv1x7oHEbJzXbFCXuJYmEyHpp6-QDs',
    appId: '1:158448736984:android:118754c2a5de39d19a55ad',
    messagingSenderId: '158448736984',
    projectId: 'nextstep-d7965',
    storageBucket: 'nextstep-d7965.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDqvvubxsNpe16YvmH1W4C2UxLltnaFDwE',
    appId: '1:158448736984:ios:3933dcb7f916b0419a55ad',
    messagingSenderId: '158448736984',
    projectId: 'nextstep-d7965',
    storageBucket: 'nextstep-d7965.firebasestorage.app',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDqvvubxsNpe16YvmH1W4C2UxLltnaFDwE',
    appId: '1:158448736984:ios:3933dcb7f916b0419a55ad',
    messagingSenderId: '158448736984',
    projectId: 'nextstep-d7965',
    storageBucket: 'nextstep-d7965.firebasestorage.app',
    iosBundleId: 'com.example.app',
  );

}