# Generated by Django 4.2.30 on 2026-05-30 05:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('firebase_uid', models.CharField(max_length=128, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('full_name', models.CharField(blank=True, max_length=200, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('avatar_url', models.TextField(blank=True, null=True)),
                ('user_type', models.CharField(choices=[('student', 'student'), ('parent', 'parent'), ('counsellor', 'counsellor'), ('school_admin', 'school_admin')], max_length=20)),
                ('subscription_tier', models.CharField(choices=[('free', 'free'), ('premium', 'premium'), ('school', 'school')], default='free', max_length=20)),
                ('subscription_expires_at', models.DateTimeField(blank=True, null=True)),
                ('parental_consent_given', models.BooleanField(default=False)),
                ('parental_consent_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='SchoolOrganisation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('school', 'school'), ('coaching_institute', 'coaching_institute'), ('college', 'college')], max_length=30)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('licence_seats', models.IntegerField(default=0)),
                ('licence_expires_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'school_organisations',
            },
        ),
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('academic_stage', models.CharField(choices=[('grade_8_9', 'grade_8_9'), ('grade_10', 'grade_10'), ('grade_11_12_science', 'grade_11_12_science'), ('grade_11_12_commerce', 'grade_11_12_commerce'), ('grade_11_12_arts', 'grade_11_12_arts'), ('college_year_1_2', 'college_year_1_2')], max_length=30)),
                ('grade_or_year', models.CharField(blank=True, max_length=10, null=True)),
                ('school_name', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('career_clarity', models.CharField(blank=True, choices=[('clear', 'clear'), ('few_options', 'few_options'), ('none', 'none'), ('wants_to_explore', 'wants_to_explore')], max_length=30, null=True)),
                ('pressure_level', models.CharField(blank=True, choices=[('high', 'high'), ('some', 'some'), ('low', 'low'), ('very_high', 'very_high')], max_length=20, null=True)),
                ('career_awareness_level', models.CharField(blank=True, choices=[('narrow', 'narrow'), ('moderate', 'moderate'), ('broad', 'broad'), ('focused', 'focused')], max_length=20, null=True)),
                ('profiler_completed', models.BooleanField(default=False)),
                ('profiler_completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'student_profiles',
            },
        ),
        migrations.CreateModel(
            name='SchoolMembership',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('student', 'student'), ('counsellor', 'counsellor'), ('admin', 'admin')], max_length=20)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='users.schoolorganisation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='school_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'school_memberships',
            },
        ),
        migrations.AddConstraint(
            model_name='schoolmembership',
            constraint=models.UniqueConstraint(fields=('user', 'organisation'), name='unique_school_membership'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['firebase_uid'], name='users_firebase_uid_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['email'], name='users_email_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['subscription_tier'], name='users_subscription_tier_idx'),
        ),
    ]
