"""Initial schema

Revision ID: 6839c4ffeebd
Revises: 
Create Date: 2026-05-30 14:45:31.699913

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6839c4ffeebd'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('career_clusters',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('q24_description', sa.Text(), nullable=False),
    sa.Column('domain_ids', postgresql.ARRAY(sa.UUID()), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('career_domains',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('slug', sa.String(length=80), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('short_name', sa.String(length=60), nullable=False),
    sa.Column('india_relevance', sa.String(length=20), nullable=False),
    sa.Column('growth_forecast_2035', sa.String(length=20), nullable=False),
    sa.Column('entry_path_summary', sa.String(length=300), nullable=False),
    sa.Column('display_order', sa.SmallInteger(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('learning_resources',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('provider', sa.String(length=150), nullable=False),
    sa.Column('resource_type', sa.String(length=30), nullable=False),
    sa.Column('career_ids', postgresql.ARRAY(sa.UUID()), nullable=True),
    sa.Column('skill_tags', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('is_free', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('subscription_plans',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('price_paise', sa.Integer(), nullable=False),
    sa.Column('duration_days', sa.Integer(), nullable=True),
    sa.Column('features', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('careers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('one_liner', sa.String(length=300), nullable=False),
    sa.Column('domain_id', sa.UUID(), nullable=False),
    sa.Column('dimension_tags', postgresql.ARRAY(sa.String(length=2)), nullable=False),
    sa.Column('india_viability', sa.String(length=20), nullable=False),
    sa.Column('future_score', sa.SmallInteger(), nullable=False),
    sa.Column('future_score_reasoning', sa.Text(), nullable=True),
    sa.Column('typical_day', sa.Text(), nullable=True),
    sa.Column('skills_needed', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('entry_paths', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('salary_entry_min_paise', sa.BigInteger(), nullable=True),
    sa.Column('salary_entry_max_paise', sa.BigInteger(), nullable=True),
    sa.Column('salary_mid_min_paise', sa.BigInteger(), nullable=True),
    sa.Column('salary_mid_max_paise', sa.BigInteger(), nullable=True),
    sa.Column('salary_senior_min_paise', sa.BigInteger(), nullable=True),
    sa.Column('salary_senior_max_paise', sa.BigInteger(), nullable=True),
    sa.Column('related_career_ids', postgresql.ARRAY(sa.UUID()), nullable=True),
    sa.Column('is_emerging', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_reviewed_at', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['domain_id'], ['career_domains.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_index('careers_domain_idx', 'careers', ['domain_id'], unique=False)
    op.create_index('careers_future_score_idx', 'careers', ['future_score'], unique=False)
    op.create_index('careers_india_viability_idx', 'careers', ['india_viability'], unique=False)
    op.create_index('careers_slug_idx', 'careers', ['slug'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('profiler_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('session_number', sa.SmallInteger(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('total_questions', sa.SmallInteger(), nullable=False),
    sa.Column('questions_answered', sa.SmallInteger(), nullable=False),
    sa.Column('questions_skipped', sa.SmallInteger(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('time_taken_seconds', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('profiler_sessions_status_idx', 'profiler_sessions', ['status'], unique=False)
    op.create_index('profiler_sessions_user_idx', 'profiler_sessions', ['user_id'], unique=False)
    op.create_table('subscription_transactions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('plan_id', sa.UUID(), nullable=False),
    sa.Column('razorpay_order_id', sa.String(length=200), nullable=True),
    sa.Column('razorpay_payment_id', sa.String(length=200), nullable=True),
    sa.Column('amount_paise', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['subscription_plans.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('razorpay_order_id')
    )
    op.create_table('ai_conversations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('conversation_type', sa.String(length=20), nullable=False),
    sa.Column('career_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(length=300), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_message_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('message_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['career_id'], ['careers.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ai_conversations_type_idx', 'ai_conversations', ['conversation_type'], unique=False)
    op.create_index('ai_conversations_user_idx', 'ai_conversations', ['user_id'], unique=False)
    op.create_table('analytics_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('session_id', sa.String(length=100), nullable=True),
    sa.Column('event_name', sa.String(length=100), nullable=False),
    sa.Column('properties', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('career_id', sa.UUID(), nullable=True),
    sa.Column('organisation_id', sa.UUID(), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['career_id'], ['careers.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('analytics_events_event_idx', 'analytics_events', ['event_name'], unique=False)
    op.create_index('analytics_events_occurred_idx', 'analytics_events', ['occurred_at'], unique=False)
    op.create_index('analytics_events_user_idx', 'analytics_events', ['user_id'], unique=False)
    op.create_table('career_saves',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('career_id', sa.UUID(), nullable=False),
    sa.Column('saved_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['career_id'], ['careers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'career_id', name='unique_career_save')
    )
    op.create_table('career_views',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('career_id', sa.UUID(), nullable=False),
    sa.Column('source', sa.String(length=30), nullable=False),
    sa.Column('viewed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('time_spent_seconds', sa.Integer(), nullable=True),
    sa.Column('reached_roadmap', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['career_id'], ['careers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('career_views_career_idx', 'career_views', ['career_id'], unique=False)
    op.create_index('career_views_user_idx', 'career_views', ['user_id'], unique=False)
    op.create_table('check_in_prompts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('career_id', sa.UUID(), nullable=True),
    sa.Column('prompt_type', sa.String(length=30), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('responded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('response', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['career_id'], ['careers.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('interest_profiles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('dimension_scores', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('top_dimensions', postgresql.ARRAY(sa.String(length=2)), nullable=False),
    sa.Column('career_cluster_weights', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('awareness_known_careers', postgresql.ARRAY(sa.String(length=100)), nullable=True),
    sa.Column('computed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['profiler_sessions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id')
    )
    op.create_index('interest_profiles_user_idx', 'interest_profiles', ['user_id'], unique=False)
    op.create_index('ip_is_active_idx', 'interest_profiles', ['is_active'], unique=False)
    op.create_table('profiler_responses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('question_code', sa.String(length=10), nullable=False),
    sa.Column('question_section', sa.String(length=30), nullable=False),
    sa.Column('selected_option_index', postgresql.ARRAY(sa.SmallInteger()), nullable=False),
    sa.Column('dimension_weights', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('skipped', sa.Boolean(), nullable=False),
    sa.Column('answered_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['profiler_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('profiler_responses_session_idx', 'profiler_responses', ['session_id'], unique=False)
    op.create_table('real_people_stories',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('career_id', sa.UUID(), nullable=False),
    sa.Column('person_name', sa.String(length=150), nullable=False),
    sa.Column('person_age', sa.SmallInteger(), nullable=True),
    sa.Column('person_city', sa.String(length=100), nullable=True),
    sa.Column('person_background', sa.String(length=300), nullable=True),
    sa.Column('story_text', sa.Text(), nullable=False),
    sa.Column('is_premium', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['career_id'], ['careers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ai_messages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('conversation_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(length=10), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('tokens_used', sa.Integer(), nullable=True),
    sa.Column('model_version', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['ai_conversations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ai_messages_convo_idx', 'ai_messages', ['conversation_id'], unique=False)
    op.create_index('ai_messages_created_at_idx', 'ai_messages', ['created_at'], unique=False)
    op.create_table('career_recommendations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('interest_profile_id', sa.UUID(), nullable=False),
    sa.Column('career_id', sa.UUID(), nullable=False),
    sa.Column('match_score', sa.SmallInteger(), nullable=False),
    sa.Column('match_tier', sa.String(length=20), nullable=False),
    sa.Column('tag_overlap_count', sa.SmallInteger(), nullable=False),
    sa.Column('display_rank', sa.SmallInteger(), nullable=False),
    sa.Column('is_novel', sa.Boolean(), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['career_id'], ['careers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['interest_profile_id'], ['interest_profiles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('career_recs_ip_idx', 'career_recommendations', ['interest_profile_id'], unique=False)
    op.create_index('career_recs_user_idx', 'career_recommendations', ['user_id'], unique=False)
    op.create_table('roadmaps',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('career_id', sa.UUID(), nullable=False),
    sa.Column('interest_profile_id', sa.UUID(), nullable=False),
    sa.Column('academic_stage', sa.String(length=30), nullable=False),
    sa.Column('generation_method', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['career_id'], ['careers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['interest_profile_id'], ['interest_profiles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('roadmap_steps',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('roadmap_id', sa.UUID(), nullable=False),
    sa.Column('step_order', sa.SmallInteger(), nullable=False),
    sa.Column('category', sa.String(length=30), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('timeframe', sa.String(length=50), nullable=True),
    sa.Column('resource_url', sa.Text(), nullable=True),
    sa.Column('resource_label', sa.String(length=200), nullable=True),
    sa.Column('is_premium', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['roadmap_id'], ['roadmaps.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('roadmap_steps_roadmap_idx', 'roadmap_steps', ['roadmap_id'], unique=False)
    op.create_table('roadmap_step_progress',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('roadmap_step_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['roadmap_step_id'], ['roadmap_steps.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'roadmap_step_id', name='unique_roadmap_step_progress')
    )
    op.create_index('roadmap_step_progress_user_idx', 'roadmap_step_progress', ['user_id'], unique=False)

    op.drop_index('school_memberships_organisation_id_3aac3245', table_name='school_memberships')
    op.drop_index('school_memberships_user_id_950e7ef7', table_name='school_memberships')
    op.drop_constraint('school_memberships_user_id_950e7ef7_fk_users_id', 'school_memberships', type_='foreignkey')
    op.drop_constraint('school_memberships_organisation_id_3aac3245_fk_school_or', 'school_memberships', type_='foreignkey')
    op.create_foreign_key(None, 'school_memberships', 'school_organisations', ['organisation_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'school_memberships', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('student_profiles_user_id_37ebcf0c_fk_users_id', 'student_profiles', type_='foreignkey')
    op.create_foreign_key(None, 'student_profiles', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.alter_column('users', 'password',
               existing_type=sa.VARCHAR(length=128),
               nullable=True)
    op.drop_index('users_email_0ea73cca_like', table_name='users')
    op.drop_index('users_firebase_uid_ae18a075_like', table_name='users')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('users_firebase_uid_ae18a075_like', 'users', ['firebase_uid'], unique=False)
    op.create_index('users_email_0ea73cca_like', 'users', ['email'], unique=False)
    op.alter_column('users', 'password',
               existing_type=sa.VARCHAR(length=128),
               nullable=False)
    op.drop_constraint(None, 'student_profiles', type_='foreignkey')
    op.create_foreign_key('student_profiles_user_id_37ebcf0c_fk_users_id', 'student_profiles', 'users', ['user_id'], ['id'], initially='DEFERRED', deferrable=True)
    op.drop_constraint(None, 'school_memberships', type_='foreignkey')
    op.drop_constraint(None, 'school_memberships', type_='foreignkey')
    op.create_foreign_key('school_memberships_organisation_id_3aac3245_fk_school_or', 'school_memberships', 'school_organisations', ['organisation_id'], ['id'], initially='DEFERRED', deferrable=True)
    op.create_foreign_key('school_memberships_user_id_950e7ef7_fk_users_id', 'school_memberships', 'users', ['user_id'], ['id'], initially='DEFERRED', deferrable=True)
    op.create_index('school_memberships_user_id_950e7ef7', 'school_memberships', ['user_id'], unique=False)
    op.create_index('school_memberships_organisation_id_3aac3245', 'school_memberships', ['organisation_id'], unique=False)
    op.create_table('django_migrations',
    sa.Column('id', sa.BIGINT(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('app', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('applied', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='django_migrations_pkey')
    )
    op.create_table('users_groups',
    sa.Column('id', sa.BIGINT(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('group_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['auth_group.id'], name='users_groups_group_id_2f3517aa_fk_auth_group_id', initially='DEFERRED', deferrable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='users_groups_user_id_f500bee5_fk_users_id', initially='DEFERRED', deferrable=True),
    sa.PrimaryKeyConstraint('id', name='users_groups_pkey'),
    sa.UniqueConstraint('user_id', 'group_id', name='users_groups_user_id_group_id_fc7788e8_uniq', postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index('users_groups_user_id_f500bee5', 'users_groups', ['user_id'], unique=False)
    op.create_index('users_groups_group_id_2f3517aa', 'users_groups', ['group_id'], unique=False)
    op.create_table('auth_group',
    sa.Column('id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=150), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='auth_group_pkey'),
    sa.UniqueConstraint('name', name='auth_group_name_key', postgresql_include=[], postgresql_nulls_not_distinct=False),
    postgresql_ignore_search_path=False
    )
    op.create_index('auth_group_name_a6ea08ec_like', 'auth_group', ['name'], unique=False)
    op.create_table('users_user_permissions',
    sa.Column('id', sa.BIGINT(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('permission_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['auth_permission.id'], name='users_user_permissio_permission_id_6d08dcd2_fk_auth_perm', initially='DEFERRED', deferrable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='users_user_permissions_user_id_92473840_fk_users_id', initially='DEFERRED', deferrable=True),
    sa.PrimaryKeyConstraint('id', name='users_user_permissions_pkey'),
    sa.UniqueConstraint('user_id', 'permission_id', name='users_user_permissions_user_id_permission_id_3b86cbdf_uniq', postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index('users_user_permissions_user_id_92473840', 'users_user_permissions', ['user_id'], unique=False)
    op.create_index('users_user_permissions_permission_id_6d08dcd2', 'users_user_permissions', ['permission_id'], unique=False)
    op.create_table('django_session',
    sa.Column('session_key', sa.VARCHAR(length=40), autoincrement=False, nullable=False),
    sa.Column('session_data', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('expire_date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('session_key', name='django_session_pkey')
    )
    op.create_index('django_session_session_key_c0390e0f_like', 'django_session', ['session_key'], unique=False)
    op.create_index('django_session_expire_date_a5c62663', 'django_session', ['expire_date'], unique=False)
    op.create_table('django_admin_log',
    sa.Column('id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('action_time', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('object_id', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('object_repr', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('action_flag', sa.SMALLINT(), autoincrement=False, nullable=False),
    sa.Column('change_message', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('content_type_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.CheckConstraint('action_flag >= 0', name='django_admin_log_action_flag_check'),
    sa.ForeignKeyConstraint(['content_type_id'], ['django_content_type.id'], name='django_admin_log_content_type_id_c4bce8eb_fk_django_co', initially='DEFERRED', deferrable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='django_admin_log_user_id_c564eba6_fk_users_id', initially='DEFERRED', deferrable=True),
    sa.PrimaryKeyConstraint('id', name='django_admin_log_pkey')
    )
    op.create_index('django_admin_log_user_id_c564eba6', 'django_admin_log', ['user_id'], unique=False)
    op.create_index('django_admin_log_content_type_id_c4bce8eb', 'django_admin_log', ['content_type_id'], unique=False)
    op.create_table('auth_permission',
    sa.Column('id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('content_type_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('codename', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['content_type_id'], ['django_content_type.id'], name='auth_permission_content_type_id_2f476e4b_fk_django_co', initially='DEFERRED', deferrable=True),
    sa.PrimaryKeyConstraint('id', name='auth_permission_pkey'),
    sa.UniqueConstraint('content_type_id', 'codename', name='auth_permission_content_type_id_codename_01ab375a_uniq', postgresql_include=[], postgresql_nulls_not_distinct=False),
    postgresql_ignore_search_path=False
    )
    op.create_index('auth_permission_content_type_id_2f476e4b', 'auth_permission', ['content_type_id'], unique=False)
    op.create_table('auth_group_permissions',
    sa.Column('id', sa.BIGINT(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('group_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('permission_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['auth_group.id'], name='auth_group_permissions_group_id_b120cbf9_fk_auth_group_id', initially='DEFERRED', deferrable=True),
    sa.ForeignKeyConstraint(['permission_id'], ['auth_permission.id'], name='auth_group_permissio_permission_id_84c5c92e_fk_auth_perm', initially='DEFERRED', deferrable=True),
    sa.PrimaryKeyConstraint('id', name='auth_group_permissions_pkey'),
    sa.UniqueConstraint('group_id', 'permission_id', name='auth_group_permissions_group_id_permission_id_0cd325b0_uniq', postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index('auth_group_permissions_permission_id_84c5c92e', 'auth_group_permissions', ['permission_id'], unique=False)
    op.create_index('auth_group_permissions_group_id_b120cbf9', 'auth_group_permissions', ['group_id'], unique=False)
    op.create_table('django_content_type',
    sa.Column('id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('app_label', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('model', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='django_content_type_pkey'),
    sa.UniqueConstraint('app_label', 'model', name='django_content_type_app_label_model_76bd3d3b_uniq', postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.drop_index('roadmap_step_progress_user_idx', table_name='roadmap_step_progress')
    op.drop_table('roadmap_step_progress')
    op.drop_index('roadmap_steps_roadmap_idx', table_name='roadmap_steps')
    op.drop_table('roadmap_steps')
    op.drop_table('roadmaps')
    op.drop_index('career_recs_user_idx', table_name='career_recommendations')
    op.drop_index('career_recs_ip_idx', table_name='career_recommendations')
    op.drop_table('career_recommendations')
    op.drop_index('ai_messages_created_at_idx', table_name='ai_messages')
    op.drop_index('ai_messages_convo_idx', table_name='ai_messages')
    op.drop_table('ai_messages')
    op.drop_table('real_people_stories')
    op.drop_index('profiler_responses_session_idx', table_name='profiler_responses')
    op.drop_table('profiler_responses')
    op.drop_index('ip_is_active_idx', table_name='interest_profiles')
    op.drop_index('interest_profiles_user_idx', table_name='interest_profiles')
    op.drop_table('interest_profiles')
    op.drop_table('check_in_prompts')
    op.drop_index('career_views_user_idx', table_name='career_views')
    op.drop_index('career_views_career_idx', table_name='career_views')
    op.drop_table('career_views')
    op.drop_table('career_saves')
    op.drop_index('analytics_events_user_idx', table_name='analytics_events')
    op.drop_index('analytics_events_occurred_idx', table_name='analytics_events')
    op.drop_index('analytics_events_event_idx', table_name='analytics_events')
    op.drop_table('analytics_events')
    op.drop_index('ai_conversations_user_idx', table_name='ai_conversations')
    op.drop_index('ai_conversations_type_idx', table_name='ai_conversations')
    op.drop_table('ai_conversations')
    op.drop_table('subscription_transactions')
    op.drop_index('profiler_sessions_user_idx', table_name='profiler_sessions')
    op.drop_index('profiler_sessions_status_idx', table_name='profiler_sessions')
    op.drop_table('profiler_sessions')
    op.drop_table('notifications')
    op.drop_index('careers_slug_idx', table_name='careers')
    op.drop_index('careers_india_viability_idx', table_name='careers')
    op.drop_index('careers_future_score_idx', table_name='careers')
    op.drop_index('careers_domain_idx', table_name='careers')
    op.drop_table('careers')
    op.drop_table('subscription_plans')
    op.drop_table('learning_resources')
    op.drop_table('career_domains')
    op.drop_table('career_clusters')
    # ### end Alembic commands ###
